### ISSUE TITLE
include press and news in request_chats to search for chat_id

### ISSUE THREAD

**Issue by mavicrz** [palverdata/palver_api#20]
Before request_chat was only important to WhatsApp and Telegram data, but now, other data sources are having their hash id of source named as chat_id, main examples are press and news. 

Also, @EnzoRobaina, chat_id in news and press returns zero documents when using "id" as a parameter, for example `id:672cc34454d86d12769785c8` has `chat_id:65d1539c61e48a0975a6406e` for news > messages collection, but  `id:65d1539c61e48a0975a6406e` returns zero document in news > chats for this query: 

![image](https://github.com/user-attachments/assets/3811a049-6554-4f57-9717-6c4cd8515e5b)

It works only if I do `query = id:65d1539c61e48a0975a6406e`:

![image](https://github.com/user-attachments/assets/f76c3e99-a78f-42be-b84d-587e9848d847)

# Tasks

### Tasks for API
- [ ] Make sure POST works with id in parameter option, not only inside the query
- [ ] Make sure news and press variables' names are consistent in time

### Tasks for R Package
- [ ]  Fix request_chat to use news and press as source parameters
- [ ] Make sure other sources are aligned to upgrade them to request_chat
- [ ] Fix request_data if necessary

**Comment by mavicrz** [comment]
searching for id in both parameter and inside query does not work for television chat_id, such as `id:6604548f9765a7970a64ee70`

![image](https://github.com/user-attachments/assets/95160eb0-983a-4e0c-b2c8-29e34ea20d97)

![image](https://github.com/user-attachments/assets/9fb6db61-8646-46b3-9d18-29fc5a7afb5c)

**Comment by mavicrz** [comment]
same for tiktok, `chat_id:6943700922024150022` when searched as parameters or inside the query of tiktok >  chats collection has zero documents:

![image](https://github.com/user-attachments/assets/ababe9a1-e4b6-40dc-9c95-599017fdef04)

**Comment by mavicrz** [comment]
for all others POST doesn't work
